# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 243)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(800, 700))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_url = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_url.setGeometry(QtCore.QRect(10, 10, 731, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_url.setFont(font)
        self.textEdit_url.setToolTip("")
        self.textEdit_url.setObjectName("textEdit_url")
        self.pushButton_go = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_go.setGeometry(QtCore.QRect(750, 10, 41, 31))
        self.pushButton_go.setObjectName("pushButton_go")
        self.pushButton_path = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_path.setGeometry(QtCore.QRect(750, 50, 41, 21))
        self.pushButton_path.setObjectName("pushButton_path")
        self.label_download_folder = QtWidgets.QLabel(self.centralwidget)
        self.label_download_folder.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.label_download_folder.setObjectName("label_download_folder")
        self.lineEdit_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_path.setGeometry(QtCore.QRect(100, 50, 641, 20))
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.comboBox_video = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_video.setGeometry(QtCore.QRect(10, 110, 781, 22))
        self.comboBox_video.setObjectName("comboBox_video")
        self.label_select_video = QtWidgets.QLabel(self.centralwidget)
        self.label_select_video.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.label_select_video.setObjectName("label_select_video")
        self.comboBox_audio = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_audio.setGeometry(QtCore.QRect(10, 170, 781, 22))
        self.comboBox_audio.setObjectName("comboBox_audio")
        self.label_select_audio = QtWidgets.QLabel(self.centralwidget)
        self.label_select_audio.setGeometry(QtCore.QRect(10, 140, 101, 20))
        self.label_select_audio.setObjectName("label_select_audio")
        self.label_filters = QtWidgets.QLabel(self.centralwidget)
        self.label_filters.setGeometry(QtCore.QRect(180, 80, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_filters.setFont(font)
        self.label_filters.setObjectName("label_filters")
        self.comboBox_resolution = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_resolution.setGeometry(QtCore.QRect(300, 80, 69, 22))
        self.comboBox_resolution.setObjectName("comboBox_resolution")
        self.pushButton_apply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_apply.setGeometry(QtCore.QRect(710, 80, 81, 21))
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.label_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_resolution.setGeometry(QtCore.QRect(240, 80, 61, 20))
        self.label_resolution.setObjectName("label_resolution")
        self.label_video_type = QtWidgets.QLabel(self.centralwidget)
        self.label_video_type.setGeometry(QtCore.QRect(380, 80, 61, 20))
        self.label_video_type.setObjectName("label_video_type")
        self.comboBox_mime_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_mime_type.setGeometry(QtCore.QRect(440, 80, 101, 22))
        self.comboBox_mime_type.setObjectName("comboBox_mime_type")
        self.label_fps = QtWidgets.QLabel(self.centralwidget)
        self.label_fps.setGeometry(QtCore.QRect(550, 80, 31, 20))
        self.label_fps.setObjectName("label_fps")
        self.comboBox_fps = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_fps.setGeometry(QtCore.QRect(580, 80, 69, 22))
        self.comboBox_fps.setObjectName("comboBox_fps")
        self.pushButton_download = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_download.setGeometry(QtCore.QRect(710, 210, 81, 21))
        self.pushButton_download.setObjectName("pushButton_download")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube Downloader"))
        self.textEdit_url.setPlaceholderText(_translate("MainWindow", "Enter YouTube URL"))
        self.pushButton_go.setText(_translate("MainWindow", "GO"))
        self.pushButton_path.setText(_translate("MainWindow", "..."))
        self.label_download_folder.setText(_translate("MainWindow", "Download Folder:"))
        self.lineEdit_path.setPlaceholderText(_translate("MainWindow", "D:\\temp"))
        self.label_select_video.setText(_translate("MainWindow", "Select video stream:"))
        self.label_select_audio.setText(_translate("MainWindow", "Select audio stream:"))
        self.label_filters.setText(_translate("MainWindow", "Filters:"))
        self.pushButton_apply.setText(_translate("MainWindow", "Apply"))
        self.label_resolution.setText(_translate("MainWindow", "Resolution:"))
        self.label_video_type.setText(_translate("MainWindow", "Video type:"))
        self.label_fps.setText(_translate("MainWindow", "FPS:"))
        self.pushButton_download.setText(_translate("MainWindow", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
